name: Bug report
description: Let us know about a bug you found.
title: "[bug]"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Reproduction steps
      description: |
        Steps to reproduce the behavior.
        1. Call `list_keys` method
        2. Pass x, y, and z as arguments
        3. Observe the error 
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual behavior
      description: The actual behavior you observed.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Any additional context the might help.
    validations:
      required: false
