name: Documentation request
description: Request an improvement to the docs.
title: "[docs]"
labels: ["documentation"]
body:
  - type: textarea
    attributes:
      label: Describe your proposed change
      description: A detailed description of the change you would like to see.
    validations:
      required: true
