name: Documentation request
description: Request an improvement to the docs.
title: "[docs]"
labels: ["documentation"]
body:
  - type: textarea
    attributes:
      label: Category of documentation update
      description: |
        What category does this change fall under. For example typo, new category addition, rephrasing, fixing broken links etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your proposed change
      description: Please describe the change & need of change with as much detail as possible.
    validations:
      required: false
