name: Feature request
description: Suggest a new feature for the project.
title: "[feat]"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Please describe your feature request
      description: A clear and concise description of what the feature is.
      placeholder: Ex. Add support for x endpoint recent implemented by unkey.
    validations:
      required: true 
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request.
    validations:
      required: false
