name: Other
description: Issues that don't fall into another category.
title: "[other]"
labels: ["random"]
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: A clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional context
      description: Any additional context surrounding this issue.
    validations:
      required: false
